name: Build and package RoBERTa-sequencing to Dockerhub

on: 
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    
    - name: set auto-install of extensions
      run: 
        az config set extension.use_dynamic_install=yes_without_prompt

    - name: install az manually
      run:
        az extension add -n azure-cli-ml

    - name: attach workspace
      run: 
        az ml folder attach -w "pratical-mlops" -g "practical-mlops-book"

    - name: retrieve the model
      run: 
        az ml model download -t "./webapp/models" --model-id "roberta-sequence:1"

    - name: Authenticate to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: build flask-app container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: alexandrehsd/flask-roberta:latest
